apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: demo-app
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/cardos0s/demo-app-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config        # injeta APP_ENV, WELCOME_MESSAGE
          env:
            - name: ConnectionStrings__Default
              value: "Host=db;Port=5432;Database=app;Username=app;Password=$(DB_PASSWORD)"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests: { cpu: 50m, memory: 96Mi }
            limits: { cpu: 300m, memory: 256Mi }
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 20
